export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_LIST_SUCCESSS = 'PRODUCT_LIST_SUCCESS'


export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'
export const PRODUCT_DETAIL_SUCCESSS = 'PRODUCT_DETAIL_SUCCESS'

export const REVIEW_REQUEST = 'REVIEW_REQUEST';
export const REVIEW_FAIL = 'REVIEW_FAIL';
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS';

export const USER_TOKEN_REQUEST = 'USER_TOKEN_REQUEST';
export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS';
export const USER_TOKEN_FAIL = 'USER_TOKEN_FAIL';

export const CART_ITEM_REQUEST = 'CART_ITEM_REQUEST';
export const CART_ITEM_SUCCESS = 'CART_ITEM_SUCCESS';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';

export const MAKE_USER_ABSENT = 'MAKE_USER_ABSENT';
export const MAKE_USER_PRESENT = 'MAKE_USER_PRESENT';
